version: "3.2"
services:
  master:
    image: trubudget/blockchain:latest
    environment:
      RPC_PORT: 8000
      ORGANIZATION: ACMECorp
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
    volumes:
      - /tmp/bcMasterVolume:/root/.multichain
    ports:
      - "7447:7447"
      - "8000:8000"
  api:
    image: trubudget/api:latest
    environment:
      RPC_HOST: master
      RPC_PORT: 8000
      ROOT_SECRET: asdf
      RPC_PASSWORD: s750SiJnj50yIrmwxPnEdSzpfGlTAHzhaUwgqKeb0G1j
      PORT: 8080
      ORGANIZATION: ACMECorp
      ORGANIZATION_VAULT_SECRET: org$ecret
      ROOT_SECRET: asdf
    links:
      - master
    ports:
      - "8080:8080"
  provisioning:
    image: trubudget/provisioning:latest
    environment:
      API_HOST: api
      API_PORT: 8080
      ENVIRONMENT_TYPE: TEST
      ROOT_SECRET: asdf
      ORGANIZATION: ACMECorp
    links:
      - api
